/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as midPaySol from "./MidPay.sol";
export type { midPaySol };
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as router from "./router";
export type { router };
import type * as util from "./util";
export type { util };
export type { MidPayCore } from "./MidPayCore";
