/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface MidPayClientInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "coreAddress"
      | "coreChainId"
      | "deposit"
      | "layerZeroEndpoint"
      | "lzReceive"
      | "owner"
      | "processed"
      | "renounceOwnership"
      | "setCoreAddress"
      | "setCoreChainId"
      | "setLayerZeroEndpoint"
      | "setTrustedRemoteLookup"
      | "setUsdc"
      | "transferOwnership"
      | "trustedRemoteLookup"
      | "usdc"
      | "withdraw"
      | "withdrawEth"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "HashAlreadyProcessed"
      | "InvalidEndpoint"
      | "LookupNotTrusted"
      | "LzCall"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "coreAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "coreChainId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "layerZeroEndpoint",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lzReceive",
    values: [BigNumberish, BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "processed",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setCoreAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setCoreChainId",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setLayerZeroEndpoint",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setTrustedRemoteLookup",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setUsdc",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "trustedRemoteLookup",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawEth",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "coreAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "coreChainId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "layerZeroEndpoint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lzReceive", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "processed", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCoreAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCoreChainId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setLayerZeroEndpoint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTrustedRemoteLookup",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setUsdc", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "trustedRemoteLookup",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawEth",
    data: BytesLike
  ): Result;
}

export namespace HashAlreadyProcessedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InvalidEndpointEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LookupNotTrustedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LzCallEvent {
  export type InputTuple = [
    srcChainId: BigNumberish,
    srcAddress: BytesLike,
    nonce: BigNumberish,
    payload: BytesLike
  ];
  export type OutputTuple = [
    srcChainId: bigint,
    srcAddress: string,
    nonce: bigint,
    payload: string
  ];
  export interface OutputObject {
    srcChainId: bigint;
    srcAddress: string;
    nonce: bigint;
    payload: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MidPayClient extends BaseContract {
  connect(runner?: ContractRunner | null): MidPayClient;
  waitForDeployment(): Promise<this>;

  interface: MidPayClientInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  coreAddress: TypedContractMethod<[], [string], "view">;

  coreChainId: TypedContractMethod<[], [bigint], "view">;

  deposit: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  layerZeroEndpoint: TypedContractMethod<[], [string], "view">;

  lzReceive: TypedContractMethod<
    [
      _srcChainId: BigNumberish,
      _srcAddress: BytesLike,
      _nonce: BigNumberish,
      _payload: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  processed: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setCoreAddress: TypedContractMethod<
    [_coreAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  setCoreChainId: TypedContractMethod<
    [_coreChainId: BigNumberish],
    [void],
    "nonpayable"
  >;

  setLayerZeroEndpoint: TypedContractMethod<
    [_layerZeroEndpoint: AddressLike],
    [void],
    "nonpayable"
  >;

  setTrustedRemoteLookup: TypedContractMethod<
    [_srcChainId: BigNumberish, _srcAddress: BytesLike],
    [void],
    "nonpayable"
  >;

  setUsdc: TypedContractMethod<[_usdc: AddressLike], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  trustedRemoteLookup: TypedContractMethod<
    [arg0: BigNumberish],
    [string],
    "view"
  >;

  usdc: TypedContractMethod<[], [string], "view">;

  withdraw: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  withdrawEth: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "coreAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "coreChainId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "layerZeroEndpoint"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "lzReceive"
  ): TypedContractMethod<
    [
      _srcChainId: BigNumberish,
      _srcAddress: BytesLike,
      _nonce: BigNumberish,
      _payload: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "processed"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setCoreAddress"
  ): TypedContractMethod<[_coreAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setCoreChainId"
  ): TypedContractMethod<[_coreChainId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setLayerZeroEndpoint"
  ): TypedContractMethod<
    [_layerZeroEndpoint: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTrustedRemoteLookup"
  ): TypedContractMethod<
    [_srcChainId: BigNumberish, _srcAddress: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setUsdc"
  ): TypedContractMethod<[_usdc: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "trustedRemoteLookup"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "usdc"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawEth"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "HashAlreadyProcessed"
  ): TypedContractEvent<
    HashAlreadyProcessedEvent.InputTuple,
    HashAlreadyProcessedEvent.OutputTuple,
    HashAlreadyProcessedEvent.OutputObject
  >;
  getEvent(
    key: "InvalidEndpoint"
  ): TypedContractEvent<
    InvalidEndpointEvent.InputTuple,
    InvalidEndpointEvent.OutputTuple,
    InvalidEndpointEvent.OutputObject
  >;
  getEvent(
    key: "LookupNotTrusted"
  ): TypedContractEvent<
    LookupNotTrustedEvent.InputTuple,
    LookupNotTrustedEvent.OutputTuple,
    LookupNotTrustedEvent.OutputObject
  >;
  getEvent(
    key: "LzCall"
  ): TypedContractEvent<
    LzCallEvent.InputTuple,
    LzCallEvent.OutputTuple,
    LzCallEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "HashAlreadyProcessed()": TypedContractEvent<
      HashAlreadyProcessedEvent.InputTuple,
      HashAlreadyProcessedEvent.OutputTuple,
      HashAlreadyProcessedEvent.OutputObject
    >;
    HashAlreadyProcessed: TypedContractEvent<
      HashAlreadyProcessedEvent.InputTuple,
      HashAlreadyProcessedEvent.OutputTuple,
      HashAlreadyProcessedEvent.OutputObject
    >;

    "InvalidEndpoint()": TypedContractEvent<
      InvalidEndpointEvent.InputTuple,
      InvalidEndpointEvent.OutputTuple,
      InvalidEndpointEvent.OutputObject
    >;
    InvalidEndpoint: TypedContractEvent<
      InvalidEndpointEvent.InputTuple,
      InvalidEndpointEvent.OutputTuple,
      InvalidEndpointEvent.OutputObject
    >;

    "LookupNotTrusted()": TypedContractEvent<
      LookupNotTrustedEvent.InputTuple,
      LookupNotTrustedEvent.OutputTuple,
      LookupNotTrustedEvent.OutputObject
    >;
    LookupNotTrusted: TypedContractEvent<
      LookupNotTrustedEvent.InputTuple,
      LookupNotTrustedEvent.OutputTuple,
      LookupNotTrustedEvent.OutputObject
    >;

    "LzCall(uint16,bytes,uint64,bytes)": TypedContractEvent<
      LzCallEvent.InputTuple,
      LzCallEvent.OutputTuple,
      LzCallEvent.OutputObject
    >;
    LzCall: TypedContractEvent<
      LzCallEvent.InputTuple,
      LzCallEvent.OutputTuple,
      LzCallEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
