/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IExternalRouter,
  IExternalRouterInterface,
} from "../../../contracts/interfaces/IExternalRouter";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint16",
        name: "_dstChainId",
        type: "uint16",
      },
      {
        internalType: "bytes",
        name: "_destination",
        type: "bytes",
      },
      {
        internalType: "bytes",
        name: "_payload",
        type: "bytes",
      },
      {
        internalType: "address payable",
        name: "_refundAddress",
        type: "address",
      },
      {
        internalType: "address",
        name: "_zroPaymentAddress",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "_adapterParams",
        type: "bytes",
      },
    ],
    name: "send",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IExternalRouter__factory {
  static readonly abi = _abi;
  static createInterface(): IExternalRouterInterface {
    return new Interface(_abi) as IExternalRouterInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IExternalRouter {
    return new Contract(address, _abi, runner) as unknown as IExternalRouter;
  }
}
