// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface IExternalRouter$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IExternalRouter";
  readonly sourceName: "contracts/interfaces/IExternalRouter.sol";
  readonly abi: [{"inputs":[{"internalType":"uint16","name":"_dstChainId","type":"uint16"},{"internalType":"bytes","name":"_destination","type":"bytes"},{"internalType":"bytes","name":"_payload","type":"bytes"},{"internalType":"address payable","name":"_refundAddress","type":"address"},{"internalType":"address","name":"_zroPaymentAddress","type":"address"},{"internalType":"bytes","name":"_adapterParams","type":"bytes"}],"name":"send","outputs":[],"stateMutability":"nonpayable","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/interfaces/IExternalRouter.sol";
  readonly buildInfoId: "solc-0_8_28-48349c0849f22d08fc7eb89c077c04140fd000ea";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IExternalRouter"]: IExternalRouter$Type;
    ["contracts/interfaces/IExternalRouter.sol:IExternalRouter"]: IExternalRouter$Type;
  }
}